PM := {{pm}}

.PHONY: install dev build start test lint format check

install:
	$(PM) install

dev:
	$(PM) run dev

build:
	$(PM) run build

start:
	$(PM) run start

test:
	$(PM) test

lint:
	$(PM) run lint

format:
	$(PM) run format

check:
	$(PM) run check
